# Generated by Django 5.0.1 on 2024-01-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('moderator', 'moderator'), ('student', 'student'), ('teacher', 'teacher')], default='student', max_length=10, verbose_name='user_role'),
        ),
    ]
